steps:
- name: 'python:3.9-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install matplotlib numpy
      pip install -r requirements.txt
      python -m unittest discover -s . -p "test_*.py"

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/plot-population', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/plot-population']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'plot-population'
    - '--image'
    - 'gcr.io/$PROJECT_ID/plot-population'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'